[target.'cfg(all(target_arch = "arm", target_os = "none"))']
# Use probe-rs for flashing and debugging
runner = "probe-rs run --chip STM32L475VGTx"

rustflags = [
    # Required for Embassy
    "-C", "link-arg=-Tlink.x",
    "-C", "link-arg=-Tdefmt.x",
]

[build]
target = "thumbv7em-none-eabihf"

[env]
DEFMT_LOG = "debug"
